### PR TITLE
update schnorrkel to 0.11.4

### PR DESCRIPTION
**Pull request by andresilva**
To align with https://github.com/paritytech/polkadot-sdk/pull/2524.

### CODE REVIEW

**Comment by andresilva** [comment]
Let's wait until the other PR is properly tested and merged.

**Review by davxy — APPROVED** [review]

**Comment by nazar-pc** [comment]
Would be nice to have a new release with this change

**Comment by nazar-pc** [comment]
Friendly ping, is there something preventing this from being released on crates.io?

**Comment by andresilva** [comment]
Sorry for the delay, I just released v0.4.6. Unrelated but I'll probably go ahead with #17 next.

**Pull request merged**
